galaxy_info:
  author: "Daniel Shepherd, Matt Shepherd, Bas Meijeri, amunter, daswars"
  description: "Apply RHEL 7 CIS Baseline"
  company: "MindPoint Group"
  license: MIT
  min_ansible_version: 2.2

  platforms:
  - name: EL
    versions:
      - 7

  galaxy_tags:
    - system
    - security
    - cis
    - hardening

dependencies: []
